function val = PrincipalStressLineStruct()
	val = struct(...
		'length',						0,	...
		'midPointPosition',				0,	...		
		'phyCoordList',					[], ...
		'eleIndexList',					[], ...
		'paraCoordList',				[], ...
		'cartesianStressList',			[],	...
		'vonMisesStressList',			[], ...
		'principalStressList', 			[], ...
		'tubePatchIndices',				[],	...
		'RibbonPatchIndices',			[],	...
		'RibbonOutlinePatchIndices',	[]	...		
	);	
end
