function CreatePatchesForVis(lineWidthTube, lineWidthRibbon)
	global majorPSLpool_; global mediumPSLpool_; global minorPSLpool_;
	global tubeShapedPSLs_Patches_; 
	global ribbonShapedPSLs_Patches_;
	global majorPSLs_Tube_PatchIndices_; global mediumPSLs_Tube_PatchIndices_; global minorPSLs_Tube_PatchIndices_;
	global majorPSLs_Ribbon_PatchIndices_; global minorPSLs_Ribbon_PatchIndices_;
	
	tubeShapedPSLs_Patches_ = struct(	...
		'majorPatchX',			[],	...
		'majorPatchY',			[],	...
		'majorPatchZ',			[],	...		
		'majorPatchC',			[],	...	
		'mediumPatchX',			[],	...
		'mediumPatchY',			[],	...
		'mediumPatchZ',			[],	...		
		'mediumPatchC',			[],	...	
		'minorPatchX',			[],	...
		'minorPatchY',			[],	...
		'minorPatchZ',			[],	...		
		'minorPatchC',			[]	...			
	); 
	ribbonShapedPSLs_Patches_ = struct(	...
		'majorPatchX',					[],	...
		'majorPatchY',					[],	...
		'majorPatchZ',					[],	...	
		'majorPatchC',					[],	...
		'majorPatchOutlineX',			[],	...
		'majorPatchOutlineY',			[],	...
		'majorPatchOutlineZ',			[],	...
		'majorPatchX_unSmo',			[],	...
		'majorPatchY_unSmo',			[],	...
		'majorPatchZ_unSmo',			[],	...	
		'majorPatchC_unSmo',			[],	...
		'majorPatchOutlineX_unSmo',		[],	...
		'majorPatchOutlineY_unSmo',		[],	...
		'majorPatchOutlineZ_unSmo',		[],	...					
		'minorPatchX',					[],	...
		'minorPatchY',					[],	...
		'minorPatchZ',					[],	...		
		'minorPatchC',					[],	...
		'minorPatchOutlineX',			[],	...
		'minorPatchOutlineY',			[],	...
		'minorPatchOutlineZ',			[],	...
		'minorPatchX_unSmo',			[],	...
		'minorPatchY_unSmo',			[],	...
		'minorPatchZ_unSmo',			[],	...	
		'minorPatchC_unSmo',			[],	...
		'minorPatchOutlineX_unSmo',		[],	...
		'minorPatchOutlineY_unSmo',		[],	...
		'minorPatchOutlineZ_unSmo',		[]	...			
	);
	
	if ~isempty(majorPSLpool_)
		[tubeShapedPSLs_Patches_.majorPatchX, tubeShapedPSLs_Patches_.majorPatchY, tubeShapedPSLs_Patches_.majorPatchZ, ...
			tubeShapedPSLs_Patches_.majorPatchC, majorPSLs_Tube_PatchIndices_] = ...
				ExpandPSLs2Tubes(majorPSLpool_, 9, lineWidthTube);
		[ribbonShapedPSLs_Patches_.majorPatchX, ribbonShapedPSLs_Patches_.majorPatchY, ribbonShapedPSLs_Patches_.majorPatchZ, ...
			ribbonShapedPSLs_Patches_.majorPatchC, ribbonShapedPSLs_Patches_.majorPatchOutlineX, ...
				ribbonShapedPSLs_Patches_.majorPatchOutlineY, ribbonShapedPSLs_Patches_.majorPatchOutlineZ, ...
					majorPSLs_Ribbon_PatchIndices_] = ExpandPSLs2Ribbons(majorPSLpool_, lineWidthRibbon, [6 7 8], 9, 1);
		[ribbonShapedPSLs_Patches_.majorPatchX_unSmo, ribbonShapedPSLs_Patches_.majorPatchY_unSmo, ...
			ribbonShapedPSLs_Patches_.majorPatchZ_unSmo, ribbonShapedPSLs_Patches_.majorPatchC_unSmo, ...
				ribbonShapedPSLs_Patches_.majorPatchOutlineX_unSmo, ribbonShapedPSLs_Patches_.majorPatchOutlineY_unSmo, ...
					ribbonShapedPSLs_Patches_.majorPatchOutlineZ_unSmo, ~] = ...
						ExpandPSLs2Ribbons(majorPSLpool_, lineWidthRibbon, [6 7 8], 9, 0);						
	end

	if ~isempty(mediumPSLpool_)
		[tubeShapedPSLs_Patches_.mediumPatchX, tubeShapedPSLs_Patches_.mediumPatchY, tubeShapedPSLs_Patches_.mediumPatchZ, ...
			tubeShapedPSLs_Patches_.mediumPatchC, mediumPSLs_Tube_PatchIndices_] = ...
				ExpandPSLs2Tubes(mediumPSLpool_, 5, lineWidthTube);
		[ribbonShapedPSLs_Patches_.mediumPatchX, ribbonShapedPSLs_Patches_.mediumPatchY, ribbonShapedPSLs_Patches_.mediumPatchZ, ...
			ribbonShapedPSLs_Patches_.mediumPatchC, ribbonShapedPSLs_Patches_.mediumPatchOutlineX, ...
				ribbonShapedPSLs_Patches_.mediumPatchOutlineY, ribbonShapedPSLs_Patches_.mediumPatchOutlineZ, ...
					mediumPSLs_Ribbon_PatchIndices_] = ExpandPSLs2Ribbons(mediumPSLpool_, lineWidthRibbon, [2 3 4], 5, 1);
		[ribbonShapedPSLs_Patches_.mediumPatchX_unSmo, ribbonShapedPSLs_Patches_.mediumPatchY_unSmo, ...
			ribbonShapedPSLs_Patches_.mediumPatchZ_unSmo, ribbonShapedPSLs_Patches_.mediumPatchC_unSmo, ...
				ribbonShapedPSLs_Patches_.mediumPatchOutlineX_unSmo, ribbonShapedPSLs_Patches_.mediumPatchOutlineY_unSmo, ...
					ribbonShapedPSLs_Patches_.mediumPatchOutlineZ_unSmo, ~] = ...
						ExpandPSLs2Ribbons(mediumPSLpool_, lineWidthRibbon, [2 3 4], 5, 0);					
	end
	
	if ~isempty(minorPSLpool_)
		[tubeShapedPSLs_Patches_.minorPatchX, tubeShapedPSLs_Patches_.minorPatchY, tubeShapedPSLs_Patches_.minorPatchZ, ...
			tubeShapedPSLs_Patches_.minorPatchC, minorPSLs_Tube_PatchIndices_] = ...
				ExpandPSLs2Tubes(minorPSLpool_, 1, lineWidthTube);
		[ribbonShapedPSLs_Patches_.minorPatchX, ribbonShapedPSLs_Patches_.minorPatchY, ribbonShapedPSLs_Patches_.minorPatchZ, ...
			ribbonShapedPSLs_Patches_.minorPatchC, ribbonShapedPSLs_Patches_.minorPatchOutlineX, ...
				ribbonShapedPSLs_Patches_.minorPatchOutlineY, ribbonShapedPSLs_Patches_.minorPatchOutlineZ, ...
					minorPSLs_Ribbon_PatchIndices_] = ExpandPSLs2Ribbons(minorPSLpool_, lineWidthRibbon, [6 7 8], 1, 1);
		[ribbonShapedPSLs_Patches_.minorPatchX_unSmo, ribbonShapedPSLs_Patches_.minorPatchY_unSmo, ...
			ribbonShapedPSLs_Patches_.minorPatchZ_unSmo, ribbonShapedPSLs_Patches_.minorPatchC_unSmo, ...
				ribbonShapedPSLs_Patches_.minorPatchOutlineX_unSmo, ribbonShapedPSLs_Patches_.minorPatchOutlineY_unSmo, ...
					ribbonShapedPSLs_Patches_.minorPatchOutlineZ_unSmo, ~] = ...
						ExpandPSLs2Ribbons(minorPSLpool_, lineWidthRibbon, [6 7 8], 1, 0);					
	end	
end