%% This script declares some global variables for this program
global dataName_; 
global GPU_; GPU_ = 'OFF';
global meshType_; 
global vtxLowerBound_; 
global vtxUpperBound_; 
global nelx_; 
global nely_; 
global nelz_; 
global numNodes_;
global nodeCoords_; 
global numEles_; 
global eNodMat_;
global eleState_; 
global nodState_; 
global nodStruct_; 
global cartesianStressField_; 
global nodeLoadVec_; 
global fixedNodes_; 	
global eleSize_; 
global silhouetteStruct_; 
global originalValidNodeIndex_; 
global solidElements_; 

global tracingStepWidth_; tracingStepWidth_ = 1;
global seedPointsHistory_; seedPointsHistory_ = [];
global seedPoints_; seedPoints_ = [];
global seedPointsValence_; seedPointsValence_ = [];
global seedSpan4VolumeOptCartesianMesh_;
global mergeTrigger_; mergeTrigger_ = 0;
global relaxedFactor_; relaxedFactor_ = 1;
global snappingOpt_; snappingOpt_ = 'OFF';
global minLengthVisiblePSLs_; minLengthVisiblePSLs_ = 20;
global interceptionThreshold_; interceptionThreshold_ = 20;

global majorPSLpool_; majorPSLpool_ = PrincipalStressLineStruct();;
global minorPSLpool_; minorPSLpool_ = PrincipalStressLineStruct();;
global majorCoordList_; majorCoordList_ = [];
global minorCoordList_; minorCoordList_ = [];
global majorHierarchy_; majorHierarchy_ = [];
global minorHierarchy_; minorHierarchy_ = [];
global majorPSLindexList_;
global minorPSLindexList_;	